#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

readonly TASKS_HOME=${TASKS_HOME:-$(pwd)}
readonly TASKS_LOGFILE=${TASKS_LOGFILE:-"$(pwd)/tasks.log"}
readonly TASKS_PIDFILE=${TASKS_PIDFILE:-'/var/run/taskd.pid'}

export TASKS_CLIENT_SECRET=${TASKS_CLIENT_SECRET:-"${TASKS_HOME}/client_secret.json"}
java -jar ${TASKS_HOME}/quarkus-gtasks-proxy-*-runner.jar > "${TASKS_LOGFILE}"
